### ISSUE TITLE
RSS/Atom Feed

### ISSUE THREAD

**Issue by JTBrinkmann** [JAForbes/blog#19]
would be great to have an RSS or Atom Feed, as I guess your sites qualifies as a blog. I bet posts.json could even be converted automatically to a corresponding XML file. The pros would be that people using RSS readers could more easily follow your posts.

The feed could contain the whole post's content, but just containing links to the posts would work, too.

**Comment by barneycarroll** [comment]
Github releases provide atom and RSS out of the box, so a policy of creating a release upon post could get the notification part there…

**Comment by JAForbes** [comment]
3 years late, but would definitely accept a PR 👍😂

**Comment by JAForbes** [comment]
Hey @JTBrinkmann this is done now :)

https://james-forbes.com/feed/atom
https://james-forbes.com/feed/json
https://james-forbes.com/feed/rss
